In [ ]:
#Basic Feedforward neural network for binary classification
#Regression
import numpy as np
X= np.random.rand(10000,10)
Y=4*X+8

In [ ]:
np.random.seed(0)
X=np.random.rand(3,2)
X

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [ ]:
#Step 1:Import necessary libraries
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

#Step 2:Generate some random data for demonstration
np.random.seed(0)
X=np.random.rand(100,2)
y= (X[:,0]+X[:,1]> 1).astype(int)
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [ ]:
#Step 3: Create a Sequential model
model=Sequential()

#Step 4: Add layers to the model
model.add(Dense(3,input_dim=2,activation='relu')) #Hidden layers with 3 neurons
model.add(Dense(1,activation='sigmoid')) #Output layer with 1 neuron(Binary Classification)

In [ ]:
X


array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985],
       [0.77815675, 0.87001215],
       [0.97861834, 0.79915856],
       [0.46147936, 0.78052918],
       [0.11827443, 0.63992102],
       [0.14335329, 0.94466892],
       [0.52184832, 0.41466194],
       [0.26455561, 0.77423369],
       [0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547],
       [0.66676672, 0.67063787],
       [0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077],
       [0.57019677, 0.43860151],
       [0.98837384, 0.10204481],
       [0.20887676, 0.16130952],
       [0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559],
       [0.

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [ ]:
#Step 5 :Compile the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#Step 6: Train the model
model.fit(X,y,epochs=12,batch_size=25)

#Step 7:Evaluate the model
loss,accuracy=model.evaluate(X,y)
print(f'Loss:{loss:.4f}')
print(f'Accuracy:{accuracy*100:.2f}%')

Epoch 1/12
4/4 [==============================] - 1s 4ms/step - loss: 0.6921 - accuracy: 0.5200
Epoch 2/12
4/4 [==============================] - 0s 4ms/step - loss: 0.6918 - accuracy: 0.5200
Epoch 3/12
4/4 [==============================] - 0s 163ms/step - loss: 0.6915 - accuracy: 0.5200
Epoch 4/12
4/4 [==============================] - 0s 5ms/step - loss: 0.6913 - accuracy: 0.5200
Epoch 5/12
4/4 [==============================] - 0s 6ms/step - loss: 0.6909 - accuracy: 0.5200
Epoch 6/12
4/4 [==============================] - 0s 5ms/step - loss: 0.6907 - accuracy: 0.5200
Epoch 7/12
4/4 [==============================] - 0s 6ms/step - loss: 0.6904 - accuracy: 0.5200
Epoch 8/12
4/4 [==============================] - 0s 6ms/step - loss: 0.6902 - accuracy: 0.5200
Epoch 9/12
4/4 [==============================] - 0s 5ms/step - loss: 0.6899 - accuracy: 0.5500
Epoch 10/12
4/4 [==============================] - 0s 4ms/step - loss: 0.6896 - accuracy: 0.5300
Epoch 11/12
4/4 [====================

In [ ]:
#Implement using Dataset for multiclassification
#Step 1: Import necessary libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [ ]:
#Step 2: Load and preprocess dataset
iris=load_iris()
X=iris.data
y=iris.target
y_binary=np.where(y==0,0,1) #Converting to binary classification

#One Hot encoding the binary labels
y_binary=to_categorical(y_binary)

#Split data into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y_binary,test_size=0.2,random_state=42)

In [ ]:
feature_names=iris.feature_names
print("Feature Names: ",feature_names)
import pandas as pd
Features=pd.DataFrame(X)
Features

Feature Names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
#Step 3:Create a sequential model
model=Sequential()

#Step 4: Add layers to the model
model.add(Dense(8,input_dim=4,activation='relu')) #Hidden layers with 8 neurons
model.add(Dense(2,activation='softmax')) #Output layer with 3 neuron(Multi-Classification)

#Step 5: Compiling the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

#Step 6: Train the model
model.fit(X_train,y_train,epochs=100,batch_size=20)

Epoch 1/100
6/6 [==============================] - 1s 3ms/step - loss: 0.4766 - accuracy: 0.9083
Epoch 2/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4510 - accuracy: 0.7833
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4334 - accuracy: 0.7083
Epoch 4/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4208 - accuracy: 0.7000
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4101 - accuracy: 0.7000
Epoch 6/100
6/6 [==============================] - 0s 3ms/step - loss: 0.3988 - accuracy: 0.7000
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 0.3877 - accuracy: 0.7417
Epoch 8/100
6/6 [==============================] - 0s 3ms/step - loss: 0.3766 - accuracy: 0.7667
Epoch 9/100
6/6 [==============================] - 0s 3ms/step - loss: 0.3660 - accuracy: 0.8000
Epoch 10/100
6/6 [==============================] - 0s 3ms/step - loss: 0.3556 - accuracy: 0.8417
Epoch 11/100
6/6 [===========

In [ ]:
#Step 7: Evaluate the model
loss,accuracy=model.evaluate(X_test,y_test)
print(f'Loss:{loss:.4f}')
print(f'Accuracy:{accuracy*100:.2f}%')

1/1 [==============================] - 0s 148ms/step - loss: 0.0272 - accuracy: 1.0000
Loss:0.0272
Accuracy:100.00%


In [ ]:
#Print the feauture names
feature_names=iris.feature_names
print("Feature Names: ",feature_names)

Feature Names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
#Get the learned weights from first layer
weights=model.layers[0].get_weights()[0]

#print feature importance based on learned weights
feature_importance=np.mean(np.abs(weights),axis=0)
print("Feature Importance: ",feature_importance)
print("Accuracy: ",accuracy)

Feature Importance:  [0.29058084 0.59250563 0.37794858 0.25042617 0.6069544  0.28681388
 0.45871928 0.389786  ]
Accuracy:  1.0


In [ ]:
#Identify the index of most important feature
most_important_feature_index=np.argmax(feature_importance)
print("Index of most important feature: ",most_important_feature_index)

Index of most important feature:  4
